### PR TITLE
Fixes duplicate definitions of statics and object properties not causing a compile-time error

### LINKED ISSUE #742: A global var named `vars` can be defined
You can define a global var named `vars` which shadows the `global.vars` list. This should be a compile error.

```
var/test1 = 10
var/test2 = "ABC"
var/vars = list("A" = 1, "B" = 2)
/world/New()
    ..()
    for (var/i in global.vars)
        world.log << "[i]: [global.vars[i]]"
```

Outputs:
```
[INFO] world.log: A: 1
[INFO] world.log: B: 2
```

### LINKED ISSUE #770: Duplicate definitions of object properties do not cause an error
Doing the following:
```dm
/datum/A
   var/x
/datum/A/B
   var/x
```
Does not cause any error or warning.

This is related to #742; `DMObjectBuilder` just doesn't do any checking to see if its statics or properties are being redefined or not.

### PR DESCRIPTION
**Pull request by Altoids1**
image

## Summary
Fixes #742 and fixes #770 by implementing some duplication detection in `DMObjectBuilder`. 

While investigating `global.vars`, I realized that DMObjectBuilder just doesn't do any dupe checking for ANY variable it makes, so I added that.

In addition, I noticed that the `IsGlobal` and `IsTopLevel` booleans for VarDeclInfo weren't really useful for anything, since both end up being grammatically synonymous with being a static.

Adding this new error detection actually *discovered* a couple duped definitions in the DMStandard, so I cleaned those up too.

## Changelog
- Fixed duplicated definitions of statics or properties not causing a compile error
- Fixed duplicated definition of `global.vars` not causing an error, despite its special implementation
- Removed duplicate definitions in the DMStandard files
- Removed superfluous booleans in the `VarDeclinfo` class.

### CODE REVIEW

File: DMCompiler/DM/Visitors/DMObjectBuilder.cs [hunk 1]
```diff
@@ -72,11 +72,38 @@ class DMObjectBuilder {
...
+                    return;
+                }
+                if (_currentObject.GlobalVariables.ContainsKey(varDefinition.Name))
+                {
+                    DMCompiler.Error(new CompilerError(varDefinition.Location, $"Duplicate definition of static var {varDefinition.Name}"));
+                    variable = _currentObject.GetGlobalVariable(varDefinition.Name);
+                }
+                else //then create
+                {
+                    variable = _currentObject.CreateGlobalVariable(varDefinition.Type, varDefinition.Name, varDefinition.IsConst);
```
Comment (wixoaGit) [inline DMCompiler/DM/Visitors/DMObjectBuilder.cs:93]: This misses the case of an object having a non-global var of the same name.

File: DMCompiler/DM/Visitors/DMObjectBuilder.cs [hunk 2]
```diff
@@ -72,11 +72,38 @@ class DMObjectBuilder {
...
+            } else { // not static
+                //make sure the var doesn't already exist, first
+                if (_currentObject.HasVariable(varDefinition.Name))
+                {
+                    DMCompiler.Error(new CompilerError(varDefinition.Location, $"Duplicate definition of var {varDefinition.Name}"));
+                    variable = _currentObject.GetVariable(varDefinition.Name); // Querying for the variable twice is a bit shoddy but this is an edgy error case anyways, so
+                }
+                else
+                {
+                    variable = new DMVariable(varDefinition.Type, varDefinition.Name, false, varDefinition.IsConst);
```
Comment (wixoaGit) [inline DMCompiler/DM/Visitors/DMObjectBuilder.cs:104]: This misses the case of an object having a global var of the same name.

File: DMCompiler/DM/Visitors/DMObjectBuilder.cs [hunk 3]
```diff
@@ -72,11 +72,38 @@ class DMObjectBuilder {
...
+                if(DoesOverrideGlobalVars(varDefinition)) // Some snowflake behaviour for global.vars
+                {
+                    DMCompiler.Error(new CompilerError(varDefinition.Location, "Duplicate definition of global.vars"));
+                    //We can't salvage any part of this definiton, since global.vars doesn't technically even exist, so lets just return
+                    _currentObject = oldObject; //TODO: Does C# have deferred things, like with destructor fanciness or something?
+                    return;
+                }
+                if (_currentObject.GlobalVariables.ContainsKey(varDefinition.Name))
+                {
+                    DMCompiler.Error(new CompilerError(varDefinition.Location, $"Duplicate definition of static var {varDefinition.Name}"));
```
Comment (wixoaGit) [inline DMCompiler/DM/Visitors/DMObjectBuilder.cs:88]: Wrapping the name of the var in quotes would make the message a little clearer
```suggestion
                    DMCompiler.Error(new CompilerError(varDefinition.Location, $"Duplicate definition of static var \"{varDefinition.Name}\""));
```

File: DMCompiler/DM/Visitors/DMObjectBuilder.cs [hunk 4]
```diff
@@ -72,11 +72,38 @@ class DMObjectBuilder {
...
+                }
+                else //then create
+                {
+                    variable = _currentObject.CreateGlobalVariable(varDefinition.Type, varDefinition.Name, varDefinition.IsConst);
+                }
+            } else { // not static
+                //make sure the var doesn't already exist, first
+                if (_currentObject.HasVariable(varDefinition.Name))
+                {
+                    DMCompiler.Error(new CompilerError(varDefinition.Location, $"Duplicate definition of var {varDefinition.Name}"));
```
Comment (wixoaGit) [inline DMCompiler/DM/Visitors/DMObjectBuilder.cs:99]:
```suggestion
                    DMCompiler.Error(new CompilerError(varDefinition.Location, $"Duplicate definition of var \"{varDefinition.Name}\""));
```

**Review by wixoaGit — CHANGES_REQUESTED** [review]

**Comment by Altoids1** [comment]
Gah!!

File: DMCompiler/DM/Visitors/DMObjectBuilder.cs [hunk 5]
```diff
@@ -72,11 +72,48 @@ class DMObjectBuilder {
...
+
+                //make sure this static doesn't already exist first
+                if(DoesOverrideGlobalVars(varDefinition)) // Some snowflake behaviour for global.vars
+                {
+                    DMCompiler.Error(new CompilerError(varDefinition.Location, "Duplicate definition of global.vars"));
+                    //We can't salvage any part of this definiton, since global.vars doesn't technically even exist, so lets just return
+                    _currentObject = oldObject; //TODO: Does C# have deferred things, like with destructor fanciness or something?
+                    return;
+                }
+                if (_currentObject.HasGlobalVariable(varDefinition.Name))
```
Comment (wixoaGit) [inline DMCompiler/DM/Visitors/DMObjectBuilder.cs:86]: These checks for existing local/global variables are basically copy-pasted below. This could be moved outside, before the `if (varDefinition.IsStatic)`.

**Review by wixoaGit — CHANGES_REQUESTED** [review]

File: DMCompiler/DM/Visitors/DMObjectBuilder.cs (hunk 5 above)
Comment (Altoids1) [reply DMCompiler/DM/Visitors/DMObjectBuilder.cs]: You squash my commits _AND_ you reduce my linecount bloat? What clout can I even have now!! 😭

Comment (wixoaGit) [reply DMCompiler/DM/Visitors/DMObjectBuilder.cs]: Closed issues clout

File: DMCompiler/DM/Visitors/DMObjectBuilder.cs [hunk 6]
```diff
@@ -71,10 +71,32 @@ class DMObjectBuilder {
...
 
             _currentObject = DMObjectTree.GetDMObject(varDefinition.ObjectPath);
+            //DMObjects store two bundles of variables; the statics in GlobalVariables and the non-statics in Variables.
+            //Lets check if we're duplicating a definition, first.
+            if (_currentObject.HasGlobalVariable(varDefinition.Name))
+            {
+                DMCompiler.Error(new CompilerError(varDefinition.Location, $"Duplicate definition of static var \"{varDefinition.Name}\""));
+                variable = _currentObject.GetGlobalVariable(varDefinition.Name);
+            }
+            else if (_currentObject.HasLocalVariable(varDefinition.Name)) // Overriding a var with a static var
```
Comment (wixoaGit) [inline DMCompiler/DM/Visitors/DMObjectBuilder.cs:81]: This comment isn't necessarily correct, the var might not be static.

This will be good to merge after this is changed,

**Review by wixoaGit — CHANGES_REQUESTED** [review]

File: DMCompiler/DM/Visitors/DMObjectBuilder.cs (hunk 6 above)
Comment (Altoids1) [reply DMCompiler/DM/Visitors/DMObjectBuilder.cs:81]: third time's the charm

**Review by wixoaGit — APPROVED** [review]
