### PR TITLE
Fixes `||=` not including path info

### LINKED ISSUE #611: Doing `LogicalOrAssign` aka `||=` with an inferred `new` doesn't work
Toplevel var: `var/database/db_handler_props`
Code:
```
var/database/db_handler_props

Prop/proc/LoadSprite()
    db_handler_props ||= new("databases/props.db")
    // other code excluded
```
Error: `An inferred new requires a type!`

### PR DESCRIPTION
**Pull request by ike709**
I'm not entirely sure this is the most correct way to do this, but it fixes #611 

Also changed a random bit of code to a switch and fixed a typo.

### CODE REVIEW

File: DMCompiler/DM/Visitors/DMVisitorExpression.cs [hunk 1]
```diff
@@ -256,12 +257,12 @@ internal DMVisitorExpression(DMObject dmObject, DMProc proc, DreamPath? inferred
 
         public void VisitLogicalAndAssign(DMASTLogicalAndAssign land) {
             var lhs = DMExpression.Create(_dmObject, _proc, land.A, _inferredPath);
-            var rhs = DMExpression.Create(_dmObject, _proc, land.B, _inferredPath);
+            var rhs = DMExpression.Create(_dmObject, _proc, land.B, lhs.Path ?? _inferredPath);
```
Comment (wixoaGit) [inline DMCompiler/DM/Visitors/DMVisitorExpression.cs:260]: This should just be `lhs.Path`, similar to `VisitAssign()`

`var1 |= var2 |= new()` does not use `var1`'s type if `var2` doesn't have one.
```suggestion
            var rhs = DMExpression.Create(_dmObject, _proc, land.B, lhs.Path);
```

File: DMCompiler/DM/Visitors/DMVisitorExpression.cs [hunk 2]
```diff
@@ -256,12 +257,12 @@ internal DMVisitorExpression(DMObject dmObject, DMProc proc, DreamPath? inferred
...
             Result = new Expressions.LogicalAndAssign(land.Location, lhs, rhs);
         }
         public void VisitLogicalOrAssign(DMASTLogicalOrAssign lor) {
             var lhs = DMExpression.Create(_dmObject, _proc, lor.A, _inferredPath);
-            var rhs = DMExpression.Create(_dmObject, _proc, lor.B, _inferredPath);
+            var rhs = DMExpression.Create(_dmObject, _proc, lor.B, lhs.Path ?? _inferredPath);
```
Comment (wixoaGit) [inline DMCompiler/DM/Visitors/DMVisitorExpression.cs:265]:
```suggestion
            var rhs = DMExpression.Create(_dmObject, _proc, lor.B, lhs.Path);
```

File: DMCompiler/Compiler/DM/DMParser.cs [hunk 3]
```diff
@@ -508,34 +508,41 @@ public DMASTProcStatement ProcStatement()
...
+            if (expression != null)
+            {
+                switch (expression)
+                {
+                    case DMASTIdentifier identifier:
+                        Check(TokenType.DM_Colon);
+                        return Label(identifier);
+                    case DMASTLeftShift shift:
+                    {
+                        DMASTLeftShift leftShift = shift;
```
Comment (wixoaGit) [inline DMCompiler/Compiler/DM/DMParser.cs:520]:
```suggestion
                    case DMASTLeftShift leftShift:
                    {
```

**Review by wixoaGit — CHANGES_REQUESTED** [review]
