### PR TITLE
Parse some funky bracketed var decl syntax

### LINKED ISSUE #320: Funky bracket var declaration syntax doesn't work
`var/{flatX1=1;flatX2=flat.Width();flatY1=1;flatY2=flat.Height()}`

image

### PR DESCRIPTION
**Pull request by ike709**
Makes this: `var/{flatX1=1;flatX2=flat.Width();flatY1=1;flatY2=flat.Height()}` compile.

Seems to work for this exact example, but I'm not sure if I have the right combo of `Whitespace()` and `Newline()` shenanigans for other potential cases.

Fixes #320

### CODE REVIEW

File: DMCompiler/Compiler/DM/DMParser.cs [hunk 1]
```diff
@@ -592,7 +592,26 @@ public DMASTProcStatement ProcStatement()
...
+                bool isIndented = Check(TokenType.DM_Indent);
+
+                List<DMASTProcStatementVarDeclaration> varDeclarations = new();
+                while (!Check(isIndented ? TokenType.DM_Dedent : TokenType.DM_RightCurlyBracket)) {
+                    DMASTProcStatementVarDeclaration[] varDecl = ProcVarEnd(true, path: varPath);
+                    Check(TokenType.DM_Semicolon);
+                    if (varDecl == null) Error("Expected a var declaration");
+
+                    varDeclarations.AddRange(varDecl);
+                    Newline();
```
Comment (ZeWaka) [inline DMCompiler/Compiler/DM/DMParser.cs:607]: why not also check for whitespace here? ex.
```
var/{flatX1=1; flatX2=2}
```

Comment (ike709) [reply DMCompiler/Compiler/DM/DMParser.cs:607]:
```suggestion
                    Whitespace();
                    Newline();
```

File: DMCompiler/Compiler/DM/DMParser.cs [hunk 2]
```diff
@@ -592,7 +592,26 @@ public DMASTProcStatement ProcStatement()
...
 
                 return varDeclarations.ToArray();
-            } else if (hasNewline) {
+            } else if (Check(TokenType.DM_LeftCurlyBracket)) {
+                Whitespace();
+                Newline();
+                bool isIndented = Check(TokenType.DM_Indent);
+
+                List<DMASTProcStatementVarDeclaration> varDeclarations = new();
+                while (!Check(isIndented ? TokenType.DM_Dedent : TokenType.DM_RightCurlyBracket)) {
```
Comment (ike709) [inline DMCompiler/Compiler/DM/DMParser.cs:601]:
```suggestion
                List<DMASTProcStatementVarDeclaration> varDeclarations = new();
                TokenType type = isIndented ? TokenType.DM_Dedent : TokenType.DM_RightCurlyBracket;
                while (!Check(type)) {
```

File: DMCompiler/Compiler/DM/DMParser.cs [hunk 3]
```diff
@@ -592,7 +592,28 @@ public DMASTProcStatement ProcStatement()
...
+                List<DMASTProcStatementVarDeclaration> varDeclarations = new();
+                TokenType type = isIndented ? TokenType.DM_Dedent : TokenType.DM_RightCurlyBracket;
+                while (!Check(type)) {
+                    DMASTProcStatementVarDeclaration[] varDecl = ProcVarEnd(true, path: varPath);
+                    Check(TokenType.DM_Semicolon);
+                    if (varDecl == null) Error("Expected a var declaration");
+
+                    varDeclarations.AddRange(varDecl);
+                    Whitespace();
+                    Newline();
```
Comment (wixoaGit) [inline DMCompiler/Compiler/DM/DMParser.cs:609]: `Delimiter()` is a better fit for this, it matches both newlines and semicolons.
```suggestion
                    Delimiter();
                    Whitespace();
                    if (varDecl == null) Error("Expected a var declaration");

                    varDeclarations.AddRange(varDecl);
```

File: DMCompiler/Compiler/DM/DMParser.cs [hunk 4]
```diff
@@ -592,7 +592,28 @@ public DMASTProcStatement ProcStatement()
...
+                }
+
+                if (isIndented) Consume(TokenType.DM_RightCurlyBracket, "Expected '}'");
```
Comment (wixoaGit) [inline DMCompiler/Compiler/DM/DMParser.cs:612]: A newline comes before `}` tokens.
```suggestion
                if (isIndented) {
                    Newline();
                    Consume(TokenType.DM_RightCurlyBracket, "Expected '}'");
                }
```

**Review by wixoaGit — CHANGES_REQUESTED** [review]

**Review by wixoaGit — APPROVED** [review]
