### PR TITLE
Fixes a few exceptions

### LINKED ISSUE #557: Setting the value of `src` causes an exception
`Assign()` can't cope with it, causing an exception in `PeekIdentifier()`

### PR DESCRIPTION
**Pull request by ike709**
Does a few things:
1. Makes sure a turf's loc is set before init to fix issues in New()
2. Adds the ability to modify an actual variable value. Fixes (partially) #556
3. Made Atom's OnVariableSet() a switch
4. `src` can be set to a DreamObject. Fixes #557

### CODE REVIEW

File: OpenDreamRuntime/DreamMapManager.cs [hunk 1]
```diff
@@ -139,21 +139,25 @@ public struct Cell {
...
                     turf = CreateMapObject(cellDefinition.Turf);
+                    SetTurf(x, y, block.Z, turf);
+                    SetArea(x, y, block.Z, area);
+                    turf.InitSpawn(new DreamProcArguments(new() {DreamValue.Null}));
                 } else {
                     turf = _dreamManager.ObjectTree.CreateObject(_defaultTurf);
+                    SetTurf(x, y, block.Z, turf);
+                    SetArea(x, y, block.Z, area);
                     turf.InitSpawn(new DreamProcArguments(null));
                 }
```
Comment (wixoaGit) [inline OpenDreamRuntime/DreamMapManager.cs:156]: This repeated code could be moved outside the if/else
```suggestion
                } else {
                    turf = _dreamManager.ObjectTree.CreateObject(_defaultTurf);
                }
                
                SetTurf(x, y, block.Z, turf);
                SetArea(x, y, block.Z, area);
                turf.InitSpawn(new DreamProcArguments(null));
                    
```

File: OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectAtom.cs [hunk 2]
```diff
@@ -36,94 +35,119 @@ class DreamMetaObjectAtom : DreamMetaObjectDatum {
...
+                        appearance.PixelOffset.Y = variableValue.GetValueAsInteger();
+                    });
+                    break;
+                case "layer":
+                    UpdateAppearance(dreamObject, appearance => {
+                        appearance.Layer = variableValue.GetValueAsFloat();
+                    });
+                    break;
+                case "invisibility":
+                    var vis = variableValue.TryGetValueAsFloat(out var val) ? Convert.ToInt32(Math.Floor(val)) : 0;
```
Comment (wixoaGit) [inline OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectAtom.cs:74]: `TryGetValueAsInteger()` will floor a float, and sets the output value to 0 on failure
```suggestion
                    variableValue.TryGetValueAsInteger(out int vis);
```

**Review by wixoaGit — CHANGES_REQUESTED** [review]

**Review by wixoaGit — APPROVED** [review]
