### PR TITLE
Give animate its own opcode, fixes animate w/ null transform

### LINKED ISSUE #1790: `animate(transform=null)` doesn't work right
explicitly setting `transform=null` should set the transform to the identity matrix. Instead `animate()` currently treats it like transform is not passed as a param.

### PR DESCRIPTION
**Pull request by Ruzihm**
Refactors animate to be a separate opcode, and handles its arguments more directly to distinguish between provided null transform vs a missing one.

Changes `animate` to behave differently when an argument is null because it is omitted vs. a null included in the caller's arguments. Closes #1790 

Adds a unit test to test for the aforementioned animate/transform/null behavior.

### CODE REVIEW

File: OpenDreamRuntime/DreamValue.cs [hunk 1]
```diff
@@ -70,6 +76,7 @@ public static DreamValue EmptyString {
 
     private object? _refValue;
     private readonly float _floatValue;
+    private bool _defaultNull = false;
```
Comment (wixoaGit) [inline OpenDreamRuntime/DreamValue.cs]: Adding new fields to `DreamValue` is kind of a no-go since any increase to its size or complexity has heavy impacts on OpenDream's performance as a whole. This would greatly increase RAM usage as well as the time taken to copy / create these values, since it's done so often.

Comment (Ruzihm) [reply OpenDreamRuntime/DreamValue.cs]: I was afraid of that. Would it be reasonable to, say, add a new field to `DreamProcArguments` which indicates which argument indices (if any) correspond to provided nulls vs default nulls, and pass in that info via its constructors?

Currently the distinction would only be made in one `DreamProcArguments` constructor call, so maybe just make another constructor with the `providedNulls` parameter and just have it called there and leave it at that...

File: OpenDreamRuntime/Procs/ProcDecoder.cs [hunk 2]
```diff
@@ -142,6 +142,8 @@ public ITuple DecodeInstruction() {
             case DreamProcOpcode.Gradient:
             case DreamProcOpcode.Rgb:
                 return (opcode, (DMCallArgumentsType)ReadByte(), ReadInt());
+            case DreamProcOpcode.Animate:
```
Comment (wixoaGit) [inline OpenDreamRuntime/Procs/ProcDecoder.cs:144]: The bodies are the same so you can put the two cases together instead.
```suggestion
            case DreamProcOpcode.Rgb:
            case DreamProcOpcode.Animate:
```

File: DMCompiler/DM/DMCodeTree.Vars.cs [hunk 3]
```diff
@@ -86,6 +86,7 @@ private bool IsValidRightHandSide(DMCompiler compiler, DMObject dmObject, DMExpr
                 NewList => true,
                 NewPath => true,
                 Rgb => true,
+                Animate => true,
```
Comment (wixoaGit) [inline DMCompiler/DM/DMCodeTree.Vars.cs]: BYOND errors on this:
```dm
/datum/var/foo = animate(new /obj)
```
so this isn't valid on the right-hand side.
```suggestion
```

File: DMCompiler/Compiler/DM/DMParser.cs [hunk 4]
```diff
@@ -2757,6 +2757,9 @@ private void BracketWhitespace() {
 
                         return new DMASTRgb(identifier.Location, callParameters);
                     }
+                    case "animate": {
```
Comment (wixoaGit) [inline DMCompiler/Compiler/DM/DMParser.cs:2760]: This should verify that there is at least 1 argument.
```suggestion
                    case "animate": {
                        if (callParameters.Length is < 1)
                            Emit(WarningCode.InvalidArgumentCount, callLoc,
                                "Expected at least 1 argument for animate()");
                        
```
